name: Update Algolia index
on:
  push:
    branches:
      - master
jobs:
  index:
    name: Update Algolia index
    runs-on: ubuntu-latest
    steps:
      - name: Internal github app token
        id: token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: ${{ vars.SENTRY_INTERNAL_APP_ID }}
          private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.token.outputs.token }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**'
              - 'includes/**'
              - 'platform-includes/**'
            dev-docs:
              - 'develop-docs/**'
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.34'

      - uses: actions/cache@v4
        id: cache
        with:
          path: ${{ github.workspace }}/node_modules
          key: node-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile
        if: steps.cache.outputs.cache-hit != 'true'

      # bun seems to be the most straightforward way to run a TypeScript script
      # without introducing another dependency like ts-node or tsx for everyone else

      - name: Build index for user docs
        run: pnpm build && bun ./scripts/algolia.ts
        if: steps.filter.outputs.docs == 'true'
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          DOCS_INDEX_NAME: ${{ secrets.DOCS_INDEX_NAME }}
          NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
          NEXT_PUBLIC_ALGOLIA_SEARCH_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_KEY }}
          SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0
          NEXT_PUBLIC_SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0

      - name: Build index for developer docs
        run: pnpm build:developer-docs && bun ./scripts/algolia.ts
        if: steps.filter.outputs.dev-docs == 'true'
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          DOCS_INDEX_NAME: ${{ secrets.DEVELOP_DOCS_INDEX_NAME }}
          NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
          NEXT_PUBLIC_ALGOLIA_SEARCH_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_SEARCH_KEY }}
          SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0
          NEXT_PUBLIC_SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0
          NEXT_PUBLIC_DEVELOPER_DOCS: 1

      - name: Build & Update Sentry Docs Algolia Index
        env:
          ALGOLIA_WRITE_API_KEY: ${{ secrets.ALGOLIA_WRITE_API_KEY }}
        run: pnpm build && bun ./scripts/algolia.ts
        if: github.ref == 'refs/heads/master'
      - name: Build & Update Developer Docs Algolia Index
        env:
          ALGOLIA_WRITE_API_KEY: ${{ secrets.ALGOLIA_WRITE_API_KEY }}
          NEXT_PUBLIC_DEVELOPER_DOCS: '1'
        run: pnpm build:developer-docs && bun ./scripts/algolia.ts
        if: github.ref == 'refs/heads/master'
