name: Lint Docs for 404s

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Internal github app token
        id: token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: ${{ vars.SENTRY_INTERNAL_APP_ID }}
          private_key: ${{ secrets.SENTRY_INTERNAL_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ steps.token.outputs.token }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - run: pnpm install --frozen-lockfile

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**'
              - 'includes/**'
              - 'platform-includes/**'
            dev-docs:
              - 'develop-docs/**'
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Build the app
      - run: pnpm build
        if: steps.filter.outputs.docs == 'true'
        env:
          SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0
          NEXT_PUBLIC_SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0

      - run: pnpm build:developer-docs
        if: steps.filter.outputs.dev-docs == 'true'
        env:
          SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0
          NEXT_PUBLIC_SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0
          NEXT_PUBLIC_DEVELOPER_DOCS: 1

      # Start the server in the background
      - name: Start Http Server
        run: pnpm start &
        if: steps.filter.outputs.docs == 'true' || steps.filter.outputs.dev-docs == 'true'
        env:
          SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0
          NEXT_PUBLIC_SENTRY_DSN: https://examplePublicKey@o0.ingest.sentry.io/0

      - name: Lint 404s
        run: bun ./scripts/lint-404s/main.ts
        if: steps.filter.outputs.docs == 'true' || steps.filter.outputs.dev-docs == 'true'

      - name: Kill Http Server
        run: kill $(lsof -t -i:3000) || true
        if: steps.filter.outputs.docs == 'true' || steps.filter.outputs.dev-docs == 'true'
        continue-on-error: true
